Update install script to overwrite existing configuration files during extraction and add error handling for missing boot disk information, enhancing disk configuration management.

diff --git a/apps/x86_64-linux/install b/apps/x86_64-linux/install
--- a/apps/x86_64-linux/install
+++ b/apps/x86_64-linux/install
@@ -22,7 +22,7 @@ cleanup() {
 
 download_config() {
   curl -LJ0 https://github.com/xlrinn/nix/archive/testing.zip -o nix-config-main.zip
-  unzip nix-config-main.zip
+  unzip -o nix-config-main.zip
   mv nix-testing nix-config
   cd nix-config
 }
@@ -34,6 +34,17 @@ run_apply() {
     exit 1
   fi
   export USERNAME=$(cat /tmp/username.txt)
+  
+  # Get the disk from the apply script output
+  if [ -f /tmp/boot_disk.txt ]; then
+    export DISK=$(cat /tmp/boot_disk.txt)
+  else
+    echo -e "\e[1;31mError: /tmp/boot_disk.txt does not exist.\e[0m"
+    exit 1
+  fi
+  
+  # Replace disk token in disk configuration
+  sed -i "s/%DISK%/$DISK/g" modules/nixos/disk-config.nix
 }
 
 run_disko() {
